// Code generated by Prismic. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
	featured_fighters: defineAsyncComponent(() => import("./FeaturedFighters/index.vue")),
	hero_section: defineAsyncComponent(() => import("./HeroSection/index.vue")),
	latest_news: defineAsyncComponent(() => import("./LatestNews/index.vue")),
	newsletter: defineAsyncComponent(() => import("./Newsletter/index.vue")),
	sponsor_logos: defineAsyncComponent(() => import("./SponsorLogos/index.vue")),
	upcoming_event: defineAsyncComponent(() => import("./UpcomingEvent/index.vue")),
	video_highlights: defineAsyncComponent(() => import("./VideoHighlights/index.vue"))
});